### ISSUE TITLE
Update to IBM Support document needed

### ISSUE THREAD

**Issue by chuempel** [IBM/wmla-assets#48]
Hello,

could someone please update the IBM support document from here https://www.ibm.com/support/pages/node/6205973
Problem is that the Link to the pytorch_mnist.zip and pytorch_onnx.zip is no longer working.
Instead of:
https://github.com/IBM/wmla-assets/tree/master/Accelerate-Deep-Learning-Training-with-Watson-Studio-Watson-ML-and-Watson-ML-Accelerator
we need to write add a "Temp" in the URL:
https://github.com/IBM/wmla-assets/blob/master/Temp/Accelerate-Deep-Learning-Train[…]on-Studio-Watson-ML-and-Watson-ML-Accelerator

Thanks!
@kelvinlui @helena-k

**Comment by helena-k** [comment]
@chuempel @kelvinlui I've reached out to the owner of this DCF article to get this fixed. Thanks!

**Comment by helena-k** [comment]
@chuempel @kelvinlui link has been updated, closing issue.
